# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-15 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ori_id', models.CharField(blank=True, max_length=40, unique=True, verbose_name='会员Id')),
                ('nick', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='昵称')),
                ('sex', models.IntegerField(default=0, verbose_name='性别')),
                ('modify_nick_num', models.IntegerField(default=0, verbose_name='修改昵称次数')),
                ('pool_rate', models.IntegerField(default=0, verbose_name='入池率')),
                ('win_rate', models.IntegerField(default=0, verbose_name='胜率')),
                ('hand_cnt', models.IntegerField(default=0, verbose_name='总手数')),
                ('series_cnt', models.IntegerField(default=0, verbose_name='总局数')),
                ('lose_number', models.IntegerField(default=0, verbose_name='输的手数')),
                ('win_number', models.IntegerField(default=0, verbose_name='赢的手数')),
                ('chip', models.IntegerField(default=0, verbose_name='筹码')),
                ('cbet', models.IntegerField(default=0, verbose_name='持续下注')),
                ('tanpai_rate', models.IntegerField(default=0, verbose_name='摊牌率')),
                ('steal', models.IntegerField(default=0, verbose_name='偷盲率')),
                ('per', models.IntegerField(default=0, verbose_name='翻牌前加注')),
                ('total_earn', models.IntegerField(default=0, verbose_name='总盈利')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
    ]
